### ISSUE TITLE
Indicator PopupWindow not setting in coodrinatorlayout 

### ISSUE THREAD

**Issue by akyanuj** [warkiz/IndicatorSeekBar#12]
The indicator pop up doesnt move in y(vertically when scrolled) with the seekbar while using inside coordinator layout. first time   is fine but when you scroll down or up it doesnt move with seek bar(its stays fixed).
Im using nestedscrollview and appbarlayout inside coordinator layout

**Comment by warkiz** [comment]
@akyanuj hi , thanks for your issue , I fixed this and please use the lastest version. 

In some special case,  if the indicator‘s location is wrong while scrolling，you can adjust it in scroll listener by code : mIndicatorSeekBar.getIndicator( ).updateIndicator( ).
For example: 
 mAppBarLayout.addOnOffsetChangedListener(new AppBarLayout.OnOffsetChangedListener() {
            @Override
            public void onOffsetChanged(AppBarLayout appBarLayout, int verticalOffset) {
                mIndicatorSeekBar.getIndicator().updateIndicator();
            }
        });

and

 mNestedScrollView.setOnScrollChangeListener(new View.OnScrollChangeListener() {
            @Override
            public void onScrollChange(View view, int i, int i1, int i2, int i3) {
                mIndicatorSeekBar.getIndicator().updateIndicator();
            }
        });

Normally, It is no need to write more java code to adjust the indicator because indicatorSeekBar will adjust the indicator itself automatic while using in a scrollable view.

Thanks you very much.

**Comment by akyanuj** [comment]
thank you for fix!
