### ISSUE TITLE
arabic  local . problem . 

### ISSUE THREAD

**Issue by 2p-esmail** [warkiz/IndicatorSeekBar#54]
when make app local to arabic .the indicator still in . the . rigth corner of the screen and . not move  when move the progress

**Comment by warkiz** [comment]
@2p-esmail thanks , will be fixed in next version

**Comment by warkiz** [comment]
hi @2p-esmail the lastest version has add this new feature，thanks for your feekback.

**Comment by oddEvenAndroid** [comment]
I have same issue  app local to arabic .the indicator still in . the . rigth corner of the screen and . not move How are you solve this? any code need add ?

**Comment by riocallos** [comment]
I forked this repo to support Arabic (might also work for other RTL languages but have only tested it with Arabic) because it wasn't working properly for me especially with the IndicatorStayLayout like your problem it just stay on the right corner of the screen. Use setArabic(true) on your IndicatorSeekBar programmatically. Check it out here [https://github.com/riocallos/IndicatorSeekBar/tree/feature/support-arabic](url).
